cd C:/users/jadmin/Google Drive/mcbackups
echo ======= BEGIN LOG ======= >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo ======= BEGIN LOG ======= >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo ======= BEGIN LOG ======= >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo BEGIN PREP... %date% %time% >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
rmdir /s /q "C:\Users\jadmin\Documents\mcbackups\temp" >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
mkdir "C:\users\jadmin\Documents\mcbackups\temp"  >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
rmdir /s /q "C:\Users\jadmin\Google Drive\mcbackups\wk2" >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo Step 1 Complete - Purge Week2 and temp  %date% %time%  >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
mkdir "C:\users\jadmin\Google Drive\mcbackups\wk2" >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo Step 2 Complete - Create dir for Week2  %date% %time%  >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
xcopy "C:\Users\jadmin\Google Drive\mcbackups\wk1\*.*" "C:\Users\jadmin\Google Drive\mcbackups\wk2\" /E /Y /V /C >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo Step 3 Complete - Week1 pushed to Week2  %date% %time%  >> "C:\users\jadmin\Documents\mcbackups\logs\backup.log"
xcopy "C:\Users\jadmin\Google Drive\mcbackups\wk0\*.*" "C:\Users\jadmin\Google Drive\mcbackups\wk1\" /E /Y /V /C >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo Step 4 Complete - Week0 (live) pushed to Week1  %date% %time%  >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo PREP COMPLETE  %date% %time%  >> "C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
echo BEGINNING NEXT STEP... %date% %time% >> C:\Users\jadmin\Documents\mcbackups\logs\backup.log"
cd "C:\Users\jadmin\Documents\mcbackups\util"
2exec.bat